env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
settings: 
  react:
    version: detect
overrides: []
parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
  sourceType: module
ignorePatterns: 
  - vite.config.ts
  - dist
plugins:
  - react
rules:
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/semi': off
  react/react-in-jsx-scope: off
  semi: [1, always]
