env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  project: tsconfig.json
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - dist
rules:
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-misused-promises': off
  '@typescript-eslint/semi': off
  semi: [1, always]
