#!/bin/sh
branch_name_incoming=$(git rev-parse --abbrev-ref HEAD)
branch_name_existing=$(cat $1 | grep -oE "\[[a-zA-Z]+\]")

[ ! -n "$branch_name_existing" ] && [ "$branch_name_incoming" != "HEAD" ] && \
  echo "[$branch_name_incoming] $(cat $1)" > $1 || \
  echo "$(cat $1)" > $1
